site_name: 'Registro Clinico'
site_description: 'Documentação do Projeto Integrador'
site_url: 'https://fabricio-moura.github.io/Registro-Clinico/'

theme:
  name: 'material'
  logo: 'images/python.jpg'
  language: 'pt'
  palette:
    primary: 'deep purple'
    accent: 'indigo'

extra:
  search:
    language: 'en, pt'
    
nav:
    - Inicio: index.md
    - Guia:
        - 'Instalação': 'install.md'
        - 'Utilização': 'utilization.md'
    - Especificações:
        - 'Banco de Dados': 'database.md'
        - 'Código': 'code.md'
    - Sobre: about.md
    

repo_name: 'fabricio-moura/Registro-Clinico'
repo_url: 'https://github.com/fabricio-moura/Registro-Clinico'

markdown_extensions:
  - codehilite